package com.jvalenc.stock.filter;

import com.eclipsesource.json.Json;
import com.eclipsesource.json.JsonObject;
import org.apache.commons.io.IOUtils;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * Created by jonat on 11/12/2017.
 */
public class AlphaVantageWebClient {

    //this key was auto generated by alpha vantage
    private String API_KEY = "B5E9IZNOFQ20MEF7";
    private String BASE_URL = "https://www.alphavantage.co/query?";
    private String AND = "&";
    private Query query;
    private String request;
    private JsonObject response;

    private void buildUrl(){
        StringBuilder sb = new StringBuilder();
        sb.append(BASE_URL);
        sb.append("function=" + query.getQueryFunction());
        sb.append(AND);
        sb.append("symbol=" + query.getSymbol());
        sb.append(AND);
        sb.append("interval=" + query.getInterval());
        sb.append(AND);
        sb.append("time_period=" + query.getTimePeriod());
        sb.append(AND);
        sb.append("series_type=" + query.getSeriesType());
        sb.append(AND);
        sb.append("apikey=" + API_KEY);

        request = sb.toString();
    }

    public void sendRequest(){
        buildUrl();

        try {
            URL url = new URL(request);
            response = Json.parse(IOUtils.toString(url, "UTF-8")).asObject();
        }catch (IOException e){
            System.err.println("There was an error with the request string: " + e.getMessage());
        }
    }
}
