package com.jvalenc.stock.web.rest;

import com.eclipsesource.json.Json;
import com.eclipsesource.json.JsonObject;
import com.jvalenc.stock.filter.Indicator;
import com.jvalenc.stock.models.QueryCriteria;
import org.apache.commons.io.IOUtils;
import org.apache.log4j.Logger;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * Created by jonat on 11/12/2017.
 */
public class AlphaVantageWebClient implements IWebClient<JsonObject>{

    //this key was auto generated by alpha vantage
    private String API_KEY = "apikey=B5E9IZNOFQ20MEF7";
    private String BASE_URL = "https://www.alphavantage.co/query?";
    private String AND = "&";
    private static Logger logger = Logger.getLogger(AlphaVantageWebClient.class);
    private static AlphaVantageWebClient INSTANCE;

    private AlphaVantageWebClient(){

    }

    /**
     * Singleton gets the instance
     * @return
     */
    public static IWebClient<JsonObject> getInstance() {
        return (INSTANCE == null)? new AlphaVantageWebClient() : INSTANCE;
    }

    /**
     * Sends the requests and gets responses
     * @param requests list of strings that will be used to make a request.
     * @return responses
     */
    @Override
    public List<JsonObject> send(List<String> requests) {
        Objects.requireNonNull(requests, "Requests cannot be null.");
        List<JsonObject> responses = new ArrayList<>();
        logger.info("Sending requests to AlphaVantage");
        requests.stream()
                .map(request -> BASE_URL + request + AND + API_KEY)
                .forEach(
                        request -> {
                            try {
                                URL url = new URL(request);
                                responses.add(Json.parse(IOUtils.toString(url, "UTF-8")).asObject());
                                //logger.info("sleeping...");
                                //API requirements to have a one sec interval between calls.
                                Thread.sleep(7000);
                                //logger.info("awake...");
                            } catch (IOException | InterruptedException e) {
                                logger.error("There was an error with the requests string: " + e.getMessage());
                            }
                        });
        logger.info("Successfully sent requests to AlphaVantage");
        return responses;
    }
}
