package com.jvalenc.stock.web.rest;

import com.eclipsesource.json.Json;
import com.eclipsesource.json.JsonObject;
import com.jvalenc.stock.filter.Indicator;
import com.jvalenc.stock.models.QueryCriteria;
import org.apache.commons.io.IOUtils;
import org.apache.log4j.Logger;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Created by jonat on 11/12/2017.
 */
public class AlphaVantageWebClient implements IWebClient<JsonObject>{

    //this key was auto generated by alpha vantage
    private String API_KEY = "apikey=";
    private String[] keys = {
            "B5E9IZNOFQ20MEF7",
            "R1TIXK7VMB28OFEP",
            "QUOM14UOBRQ0Z26M",
            "3DVHXCTGE8ZY07M5",
            "4HGO0OD8QRLN9QO2",
            "NUBJIGSJGRPFAAJM"
    };
    private String BASE_URL = "https://www.alphavantage.co/query?";
    private String AND = "&";
    private static Logger logger = Logger.getLogger(AlphaVantageWebClient.class);
    private static AlphaVantageWebClient INSTANCE;
    private AtomicInteger count;

    private AlphaVantageWebClient(){

        count = new AtomicInteger(0);
    }

    /**
     * Singleton gets the instance
     * @return
     */
    public static IWebClient<JsonObject> getInstance() {

        if (INSTANCE == null) {
            INSTANCE = new AlphaVantageWebClient();
        }
        return INSTANCE;
    }

    /**
     * Sends the requests and gets responses
     * @param requests list of strings that will be used to make a request.
     * @return responses
     */
    @Override
    public List<JsonObject> send(List<String> requests) {
        Objects.requireNonNull(requests, "Requests cannot be null.");
        List<JsonObject> responses = new ArrayList<>();
        logger.info("Sending requests to AlphaVantage");
        requests.stream()
                .map(request -> new StringBuilder().append(BASE_URL)
                        .append(request)
                        .append(AND)
                        .append(API_KEY)
                        .append(keys[count.getAndIncrement() % keys.length]).toString())
                .forEach(
                        request -> {
                            logger.info("counter at " + count.get() + " calling: " + request);
                            try {
                                //API requirements you can only have 5 calls per minute!!! ridiculous.
//                                if (count.addAndGet(1) % 4 == 0) {
//                                    logger.info("We have reached the call limit of 5 per minute. sleeping for a minute.");
//                                    Thread.sleep(61000);
//                                }
                                URL url = new URL(request);
                                responses.add(Json.parse(IOUtils.toString(url, "UTF-8")).asObject());
                            } catch (IOException  e) {
                                logger.error("There was an error with the requests string: " + e.getMessage());
                            }
                        });
        logger.info("Successfully sent requests to AlphaVantage");
        return responses;
    }
}
